//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rough.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACK
    {
        public int TRACK_ID { get; set; }
        public string TRACK_NAME { get; set; }
        public int TRACK_ARTIST { get; set; }
    
        public virtual ARTIST ARTIST { get; set; }
    }
}
